seed: 42
data_shuffle_seed : null  # TODO: check
dataset_options:
    name: StackedMNIST
    root: 'datasets/'
    num_train_images: 60000
    num_test_images: 10000
    num_targets: 2
    num_groups: 2
    prevent_class_shuffling: False
    prevent_group_shuffling: False
    dirichlet_targets_alpha: 1.0
    dirichlet_groups_alpha: 1.0
    uniform_targets: True
    uniform_groups: True
    force_targets:
    - 23
    - 45
    force_groups:
    - 0
    - 1
    force_targets_proportions: null
    force_groups_proportions: null
    force_proportions:
    - - 0.05
      - 0.45
    - - 0.45
      - 0.05
split_mode: mode3
#uniform_proportion: 0.2
batch_size: 32
epochs: 1
rounds: 1000
num_clients: 20
weight_clients: false  # TODO: check
client_opt:
    subpop_optimizer: ERM
    base_optimizer: SGD
    learning_rate: 0.1
    groupdro_eta: 1e-2
    cbloss_beta: 0.9999
    focal_gamma: 1
    dfr_reg: 0.1
server_opt:
    optimizer: FedAvg  # TODO: check
    learning_rate: 1.0
    beta_1: 0.9  # TODO: check
    beta_2: 0.99  # TODO: check
    tau: 0.000000001  # TODO: check
wandb: true
model_options:
    model_type: MobileNet
    norm_layer: gn
store_id: true
checkpoint: null