seed: 42
data_shuffle_seed : null
dirichlet_alpha: 0.5
batch_size: 24
epochs: 1
rounds: 10
num_clients: 4
weight_clients: true
norm: true
aug_crop: 24
aug_horizontal_flip: true
split_mode: homogen
client_opt:
    subpop_optimizer: ERM
    base_optimizer: SGD
    learning_rate: 1e-3
    momentum: 0.9
server_opt:
    optimizer: FedAvg
    learning_rate: 0.1
    beta_1: 0.9
    beta_2: 0.99
    tau: 0.000000001
wandb: true
model_options:
    model_type: ResNet
    norm_layer: gn
dataset_options:
    name: WaterBirds
    input_size: 224
    num_targets: 2
    num_groups: 2
