defaults:
  - machine: env
  - client_opt: all_defaults
  - server_opt: all_defaults
  - dataset_options: waterbirds
  - model_options: resnet
seed: 42
client_opt:
  epochs: 4
rounds: 10
num_clients: 4
norm: true
aug_crop: 24
aug_horizontal_flip: true
split_mode: sameratio
wandb: true
dataset_options:
    input_size: 16
eval_interval: 1
test_interval: 1
checkpoint: null
local_training_id: null