defaults:
  - machine: env
  - client_opt: all_defaults
  - server_opt: all_defaults
  - model_options: resnet
  - dataset_options: spawrious
  - override hydra/launcher: kyiv
  - _self_

hydra:
  mode: MULTIRUN
  launcher:
    cpus_per_task: 4
    mem_gb: 24
    additional_parameters:
      gres: "shard:4"

seed: 42
client_opt:
  batch_size: 32
  epochs: 1
server_opt:
  rounds: 4
dataset_options:
  input_size: 16
  num_clients: 4
  split_mode: more_expected_clients
  num_samples_per_class: null
checkpoint: null
wandb: true
