defaults:
  - machine: env
  - client_opt: all_defaults
  - server_opt: all_defaults
  - model_options: mobilenet
  - dataset_options: stackedmnist_centralized
seed: 42
dataset_options:
    root: '/home/efani/DATASETS'
client_opt:
  epochs: 100
eval_interval: 1
test_interval: 1
wandb: true
checkpoint: null