defaults:
  - machine: env
  - client_opt: all_defaults
  - server_opt: all_defaults
  - dataset_options: waterbirds
  - model_options: resnet
  - override hydra/launcher: kyiv
  - _self_

hydra:
  mode: MULTIRUN
  launcher:
    cpus_per_task: 4
    mem_gb: 24
    additional_parameters:
      gres: "shard:4"

seed: 42
client_opt:
  subpop_optimizer: ERM
  epochs: 1
server_opt:
  rounds: 10
  weight_clients: server_post_triplets_stochasticmatrix_noreplacement
wandb: false
dataset_options:
  input_size: 16
  split_mode: balancedclients
  num_clients: 4
checkpoint: null
