defaults:
  - machine: env
  - client_opt: all_defaults
  - server_opt: all_defaults
  - model_options: mobilenet
  - dataset_options: stackedmnist_federated
seed: 42
data_shuffle_seed : null  # TODO: check
dataset_options:
    root: '/home/efani/DATASETS'
split_mode: mode3
#uniform_proportion: 0.2
batch_size: 32
epochs: 1
rounds: 1000
num_clients: 20
server_opt:
wandb: true
store_id: true
checkpoint: null
local_training_id: null