defaults:
  - machine: env
  - client_opt: all_defaults
  - server_opt: all_defaults
  - dataset_options: waterbirds
  - model_options: resnet
seed: 42
client_opt:
  epochs: 4
server_opt:
  rounds: 10
wandb: true
dataset_options:
  input_size: 16
eval_interval: 1
test_interval: 1
checkpoint: null