defaults:
  - job/federated_training@_here_
  - _self_
  - machine: env
  - client_opt: all_defaults
  - server_opt: all_defaults
  - model_options: resnet
  - dataset_options: cifar10
seed: 42
client_opt:
  batch_size: 32
epochs: 1
rounds: 10
num_clients: 10
norm: true
aug_crop: 4
aug_horizontal_flip: true
split_mode: dirichlet
checkpoint: null
local_training_id: null