defaults:
  - job/federated_training@_here_
  - _self_
  - machine: env
  - client_opt: all_defaults
  - server_opt: all_defaults
  - model_options: resnet
  - dataset_options: cifar10
seed: 42
client_opt:
  batch_size: 32
  epochs: 1
server_opt:
  rounds: 200
num_clients: 10
split_mode: dirichlet
checkpoint: null