subpop_optimizer: ERM
base_optimizer: SGD
batch_size: 32
learning_rate: 1e-3
momentum: 0.9
groupdro_eta: 1e-2
cbloss_beta: 0.9999
focal_gamma: 1
dfr_reg: 0.1
fex_shallow_model: CNN
fex_epochs: 5
fex_balance_classes: true
epochs: 200
biased_trainer_epochs: 1
biased_trainer_steps: 100
left_right_trainer_epochs: 10
left_right_trainer_steps: 100
generalized_cross_entropy_q: 0.7
num_workers: 4
biased_optimizer: ERM
proximal_mu: 0.0
hcsfed_compression_rate: 1e-5
hcsfed_num_clusters: 3
hcsfed_tolerance_gc: 1e-1
hcsfed_tolerance_cl: 1e-12